security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt


    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true  
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
        
        register_admin:
            pattern:  ^/api/user/register-admin-user
            stateless: true
        
        check_users:
            pattern:  ^/api/user/check-has-users
            stateless: true
        
        login:
            pattern:  ^/api/login
            stateless: true
            json_login:
                check_path:               /api/login-check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api/
            stateless: true
            jwt:   ~


    access_control:
        - { path: ^/api/user/register-admin-user, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/check-has-users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }